


[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 12

[general]
import = [ "~/.nixos-config/config/alacritty/themes/everforest_custom.toml" ]

# [window]
# opacity = 0.5
