{ config, lib, ... }:

let
  cfg = config.modules.desktop.hyprland;
  colors = config.lib.stylix.colors;
  rgb = c: "rgb(${c})";
  rgba = c: a: "rgba(${c}${a})";
in
{
  options.modules.desktop.hyprland.stylixColors = lib.mkOption {
    type = lib.types.bool;
    default = false;
    description = "Generate ~/.config/hypr/colors.conf from Stylix Base16 colors.";
  };

  config = lib.mkIf cfg.stylixColors {
    xdg.configFile."hypr/colors.conf".text = ''
      # -------------------------------------------------
      # Hyprland colors
      # Generated by Stylix (Base16)
      # DO NOT EDIT MANUALLY
      #
      # This approach allows the user to manage Hyprland's config in hyprlang while
      # taking advantage of Stylix, rather than rebuilding Hyprland's config when a small change is made.
      # -------------------------------------------------

      # Base16 variables
      $base00 = ${rgb colors.base00}
      $base01 = ${rgb colors.base01}
      $base02 = ${rgb colors.base02}
      $base03 = ${rgb colors.base03}
      $base04 = ${rgb colors.base04}
      $base05 = ${rgb colors.base05}
      $base06 = ${rgb colors.base06}
      $base07 = ${rgb colors.base07}
      $base08 = ${rgb colors.base08}
      $base09 = ${rgb colors.base09}
      $base0A = ${rgb colors.base0A}
      $base0B = ${rgb colors.base0B}
      $base0C = ${rgb colors.base0C}
      $base0D = ${rgb colors.base0D}
      $base0E = ${rgb colors.base0E}
      $base0F = ${rgb colors.base0F}

      # Mappings
      general {
        col.active_border = $base0D
        col.inactive_border = $base03
      }

      decoration {
        shadow {
          color = ${rgba colors.base00 "99"}
        }
      }

      group {
        col.border_active = $base0D
        col.border_inactive = $base03
        col.border_locked_active = $base0C

        groupbar {
          text_color = $base05
          col.active = $base0D
          col.inactive = $base03
        }
      }

      misc {
        background_color = $base00
      }
    '';
  };
}
